nav:
  - File 1: file-1.md
  - File 2:
    - file-2.md
    - File 3:
      - file-3.md
      - File 4: file-4.md
  - File 5: file-5.md
  - File 6: file-6.md
  - File 7:
    - file-7.md
    - File 8: file-8.md
  - File 9: file-9.md
  - File 10: file-10.md
